---
- hosts: all
  tasks:
    - name: Install the cowsay package
      become: yes
      apt:
        name: cowsay
        state: present
    - name:  Test the cowsay command
      command: cowsay This definitely works!
